name: RAG_DEMO
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - snowflake-snowpark-python[pandas]==1.14.0
  - PyPDF2==2.10.5
  - ipykernel==6.28.0
  - langchain==0.0.298
  - pycryptodome==3.15.0
  - snowflake-ml-python==1.4.0
